function VisageCreateElement(attributes, text, childs, tag) {
    const element = document.createElement(tag)

    if (attributes !== undefined) {
        for(const prop in attributes) {
            element.setAttribute(prop, attributes[prop])
        }
    }

    element.appendChild(document.createTextNode(text))

    childs !== undefined ? childs.map(child => element.appendChild(child)) : null

    return element
}

const VisageSingleElement = (tag) => document.createElement(tag)

// HTML tags
const a = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "a")
const abbr = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "abbr")
const acronym = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "acronym")
const address = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "address")
const area = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "area")
const article = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "article")
const aside = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "aside")
const audio = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "audio")
const b = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "b")
const base = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "base")
const bdo = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "bdo")
const blockquote = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "blockquote")
const br = () => VisageSingleElement("br")
const button = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "button")
const canvas = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "canvas")
const caption = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "caption")
const center = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "center")
const cite = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "cite")
const code = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "code")
const col = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "col")
const colgroup = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "colgroup")
const command = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "command")
const datalist = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "datalist")
const dfn = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "dfn")
const div = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "div")
const dl = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "dl")
const dt = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "dt")
const em = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "em")
const embed = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "embed")
const fieldset = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "fieldset")
const figcaption = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "figcaption")
const figure = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "figure")
const font = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "font")
const footer = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "footer")
const form = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "form")
const frame = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "frame")
const frameset = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "frameset")
const h1 = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "h1")
const h2 = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "h2")
const h3 = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "h3")
const h4 = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "h4")
const h5 = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "h5")
const h6 = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "h6")
const head = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "head")
const header = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "header")
const hr = () => VisageSingleElement("hr")
const i = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "i")
const iframe = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "iframe")
const img = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "img")
const input = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "input")
const ins = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "ins")
const kbd = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "kbd")
const label = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "label")
const legend = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "legend")
const li = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "li")
const link = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "link")
const map = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "map")
const mark = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "mark")
const menu = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "menu")
const meta = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "meta")
const meter = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "meter")
const nav = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "nav")
const noscript = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "noscript")
const object = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "object")
const ol = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "ol")
const optgroup = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "optgroup")
const option = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "option")
const output = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "output")
const p = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "p")
const param = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "param")
const pre = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "pre")
const progress = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "progress")
const q = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "q")
const rp = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "rp")
const rt = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "rt")
const ruby = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "ruby")
const s = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "s")
const samp = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "samp")
const section = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "section")
const select = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "select")
const small = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "small")
const source = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "source")
const span = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "span")
const strike = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "strike")
const strong = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "strong")
const style = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "style")
const sub = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "sub")
const sup = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "sup")
const table = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "table")
const tbody = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "tbody")
const td = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "td")
const textarea = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "textarea")
const tfoot = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "tfoot")
const th = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "th")
const thead = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "thead")
const time = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "time")
const tr = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "tr")
const track = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "track")
const tt = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "tt")
const u = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "u")
const ul = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "ul")
const varitable = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "var")
const video = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "video")
const wbr = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "wbr")

// Visage Tags
const VisageRouter = (attributes, text, childs) => VisageCreateElement(attributes, text, childs, "VisageRouter")

// create tag
const newTag = (tag, attributes, text, childs) => VisageCreateElement(attributes, text, childs, tag)